/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_exlmoto_aaaa_AAAANativeLibProxy */

#ifndef _Included_ru_exlmoto_aaaa_AAAANativeLibProxy
#define _Included_ru_exlmoto_aaaa_AAAANativeLibProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_exlmoto_aaaa_AAAANativeLibProxy
 * Method:    AAAAJoystickButtonDown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_aaaa_AAAANativeLibProxy_AAAAJoystickButtonDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_exlmoto_aaaa_AAAANativeLibProxy
 * Method:    AAAAJoystickButtonUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_aaaa_AAAANativeLibProxy_AAAAJoystickButtonUp
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
