/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_exlmoto_aaaa_AAAANativeLibProxy */

#ifndef _Included_ru_exlmoto_aaaa_AAAANativeLibProxy
#define _Included_ru_exlmoto_aaaa_AAAANativeLibProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_exlmoto_aaaa_AAAANativeLibProxy
 * Method:    AAAANativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_aaaa_AAAANativeLibProxy_AAAANativeInit
  (JNIEnv *, jclass);

/*
 * Class:     ru_exlmoto_aaaa_AAAANativeLibProxy
 * Method:    AAAANativeDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_aaaa_AAAANativeLibProxy_AAAANativeDeinit
  (JNIEnv *, jclass);

/*
 * Class:     ru_exlmoto_aaaa_AAAANativeLibProxy
 * Method:    AAAANativeSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_aaaa_AAAANativeLibProxy_AAAANativeSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ru_exlmoto_aaaa_AAAANativeLibProxy
 * Method:    AAANativeDrawStep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_aaaa_AAAANativeLibProxy_AAANativeDrawStep
  (JNIEnv *, jclass);

/*
 * Class:     ru_exlmoto_aaaa_AAAANativeLibProxy
 * Method:    SpoutInitilizeGlobalJavaEnvPointer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_aaaa_AAAANativeLibProxy_SpoutInitilizeGlobalJavaEnvPointer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
